In [1]:
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['font.family'] ='Malgun Gothic'
plt.rcParams['axes.unicode_minus'] =False

df = pd.read_csv('https://bit.ly/ds-house-price-clean')
print(df.shape)
df.head()

'''
1. 차트 영역 만들기
plt.figure => 변수에 담을 수 있고, 기타 옵션(차트크기 figsize=(튜플), ...)
2. 차트 그리기
3. 차트 종료 : 차트를 메모리에서 제거
plt.show()
'''

(3293, 5)

   지역             규모    연도   월   분양가
0  서울          60㎡이하  2015  10  5652
1  서울    60㎡초과 85㎡이하  2015  10  5882
2  서울   85㎡초과 102㎡이하  2015  10  5721
3  서울         102㎡초과  2015  10  5879
4  인천          60㎡이하  2015  10  3488

In [ ]:
'''
차트 여러개 그리기
plt.subplot(행,열,자리)
ex)plt.subplot(3,2,6) -> 3행 2열표에서 6번째자리에 그려라

차트끼리 겹치지 않도록
plt.tight_layout()
'''

In [ ]:
'''
표 타이틀
plt.title('a_chart')
x축 라벨
plt.xlabel('x')
y축 라벨
plt.ylabel('y')
텍스트 추가
plt.text(x좌표,y좌표,'텍스트')
-> 해당좌표에 텍스트가 표현되기때문에 일반적으로는 y좌표에 +1정도를 한다.
ex)
for x,y in enumerate(a):
    plt.text(x,y+0.5,a[x])
    
ex)
plt.text(1,5,'text1')

plot(kind='barh') -> h : 그래프 가로형으로

그래프를 파일로
plt.savefig('파일이름.jpg')
차트 파일로 저장하기
plt.savefig('fig.jpg', dpi=300)
dpi=300 일반적으로 생략하고 300:인쇄용 / 일반적인 웹에서는 72이다.

라벨에 각도주기
plt.xticks(rotation=45) -> x축 라벨 45도 글자기울임
plt.yticks(rotation=45) -> y축 라벨 45도 글자기울임

그래프에 라벨주기
plt.plot(a,y,label='abc')

축에 한계(리미트)주기
plt.xlim(0,50) -> x축 0~50
plt.ylim(0,50) -> y축 0~50

그래프에 그리드주기
plt.grid()

히스토그램관련
N = 100000 #자료의수
x = np.random.randn(N) # 평균0, 표준편차가1 인수(정규분포)
plt.hist(x, bins=구간개수)
density=True -> 상대도수분포
cumulative=True -> 누적도수분포


탐색적 데이터 분석(EDA)
- 산점도 (스캐터차트) : x축, y축 모두 숫자
 : 두 숫자의 관계도를 많이 봄
- 박스프롯
'''


'''
**Markers**

=============   ===============================
character       description
=============   ===============================
``'.'``         point marker
``','``         pixel marker
``'o'``         circle marker
``'v'``         triangle_down marker
``'^'``         triangle_up marker
``'<'``         triangle_left marker
``'>'``         triangle_right marker
``'1'``         tri_down marker
``'2'``         tri_up marker
``'3'``         tri_left marker
``'4'``         tri_right marker
``'8'``         octagon marker
``'s'``         square marker
``'p'``         pentagon marker
``'P'``         plus (filled) marker
``'*'``         star marker
``'h'``         hexagon1 marker
``'H'``         hexagon2 marker
``'+'``         plus marker
``'x'``         x marker
``'X'``         x (filled) marker
``'D'``         diamond marker
``'d'``         thin_diamond marker
``'|'``         vline marker
``'_'``         hline marker
=============   ===============================

**Line Styles**

=============    ===============================
character        description
=============    ===============================
``'-'``          solid line style
``'--'``         dashed line style
``'-.'``         dash-dot line style
``':'``          dotted line style
=============    ===============================

Example format strings::

    'b'    # blue markers with default shape
    'or'   # red circles
    '-g'   # green solid line
    '--'   # dashed line with default color
    '^k:'  # black triangle_up markers connected by a dotted line

**Colors**

The supported color abbreviations are the single letter codes

=============    ===============================
character        color
=============    ===============================
``'b'``          blue
``'g'``          green
``'r'``          red
``'c'``          cyan
``'m'``          magenta
``'y'``          yellow
``'k'``          black
``'w'``          white
=============    ===============================
'''